# Generated by Django 6.0.3 on 2026-03-08 23:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('segment', models.CharField(blank=True, max_length=255, null=True)),
                ('business_type', models.CharField(blank=True, choices=[('physical', 'Físico'), ('online', 'Online'), ('hybrid', 'Híbrido')], max_length=20, null=True)),
                ('stage', models.CharField(choices=[('ideation', 'Ideação'), ('plan', 'Plano'), ('mvp', 'MVP'), ('operation', 'Operação')], default='ideation', max_length=20)),
                ('city', models.CharField(blank=True, max_length=120, null=True)),
                ('state', models.CharField(blank=True, max_length=2, null=True)),
                ('has_cnpj', models.BooleanField(default=False)),
                ('revenue_range', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessStageHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_stage', models.CharField(blank=True, choices=[('ideation', 'Ideação'), ('plan', 'Plano'), ('mvp', 'MVP'), ('operation', 'Operação')], max_length=20, null=True)),
                ('to_stage', models.CharField(choices=[('ideation', 'Ideação'), ('plan', 'Plano'), ('mvp', 'MVP'), ('operation', 'Operação')], max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_history', to='core.business')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stage_changes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('hypothesis', models.TextField()),
                ('experiment_type', models.CharField(blank=True, max_length=50, null=True)),
                ('target_audience', models.TextField(blank=True, null=True)),
                ('channels', models.TextField(blank=True, null=True)),
                ('success_metrics', models.TextField(blank=True, null=True)),
                ('expected_duration_days', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planned', 'Planejado'), ('running', 'Em andamento'), ('finished', 'Concluído'), ('cancelled', 'Cancelado')], default='planned', max_length=20)),
                ('results', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiments', to='core.business')),
            ],
        ),
        migrations.CreateModel(
            name='FormResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_type', models.CharField(choices=[('ideation', 'Ideação'), ('plan', 'Plano de Negócios'), ('mvp', 'MVP')], max_length=20)),
                ('form_version', models.CharField(default='1.0', max_length=10)),
                ('data', models.JSONField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_responses', to='core.business')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis_type', models.CharField(choices=[('ideation', 'Ideação'), ('plan', 'Plano de Negócios'), ('mvp', 'MVP')], max_length=20)),
                ('diagnosis_version', models.CharField(default='1.0', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('processing', 'Processando'), ('done', 'Concluído'), ('error', 'Erro')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('is_free', models.BooleanField(default=True)),
                ('tokens_used', models.IntegerField(blank=True, null=True)),
                ('model_name', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='core.business')),
                ('form_response', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnoses', to='core.formresponse')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StageStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ideation_started_at', models.DateTimeField(blank=True, null=True)),
                ('ideation_completed_at', models.DateTimeField(blank=True, null=True)),
                ('ideation_progress', models.PositiveIntegerField(default=0)),
                ('plan_started_at', models.DateTimeField(blank=True, null=True)),
                ('plan_completed_at', models.DateTimeField(blank=True, null=True)),
                ('plan_progress', models.PositiveIntegerField(default=0)),
                ('mvp_started_at', models.DateTimeField(blank=True, null=True)),
                ('mvp_completed_at', models.DateTimeField(blank=True, null=True)),
                ('mvp_progress', models.PositiveIntegerField(default=0)),
                ('current_stage', models.CharField(choices=[('ideation', 'Ideação'), ('plan', 'Plano'), ('mvp', 'MVP'), ('done', 'Concluído')], default='ideation', max_length=20)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stage_status', to='core.business')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('entrepreneur', 'Empreendedor'), ('mentor', 'Mentor'), ('admin', 'Admin')], default='entrepreneur', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
